sbatch experiments/any/run.sh experiments/any 0
sbatch experiments/any/run.sh experiments/any 500
sbatch experiments/any/run.sh experiments/any 1000
sbatch experiments/any/run.sh experiments/any 1500
sbatch experiments/any/run.sh experiments/any 2000
sbatch experiments/any/run.sh experiments/any 2500
sbatch experiments/any/run.sh experiments/any 3000
sbatch experiments/any/run.sh experiments/any 3500
sbatch experiments/any/run.sh experiments/any 4000
sbatch experiments/any/run.sh experiments/any 4500
sbatch experiments/any/run.sh experiments/any 5000
sbatch experiments/any/run.sh experiments/any 5500
sbatch experiments/any/run.sh experiments/any 6000
sbatch experiments/any/run.sh experiments/any 6500
sbatch experiments/any/run.sh experiments/any 7000
sbatch experiments/any/run.sh experiments/any 7500
